"""Pronunciations the voice gets wrong, fixed with Fish's phoneme tags
(CMU Arpabet, one word per tag: <|phoneme_start|>EH1 N ...<|phoneme_end|>).

audio/lexicon/kjv.tsv, one rule per line:
    pattern <TAB> arpabet <TAB> source / note
The pattern is a regular expression matched case-sensitively on whole words;
it may carry context so a heteronym is fixed only where it means one thing
("lead(?= sank)" is the metal). Only the word itself is replaced: put context
in lookarounds. Every entry needs a source (dictionary, or the reading
checked by ear) in its note.
"""
import re
from functools import lru_cache

from . import paths

FILE = paths.LEXICON / f"{paths.BIBLE}.tsv"
TAG = "<|phoneme_start|>{}<|phoneme_end|>"


@lru_cache(maxsize=None)
def rules():
    out = []
    if not FILE.exists():
        return out
    for row in FILE.read_text(encoding="utf-8").splitlines():
        if not row.strip() or row.startswith("#"):
            continue
        pattern, arpabet, *_ = row.split("\t")
        out.append((re.compile(r"(?<![\w’'-])" + pattern + r"(?![\w’'-])"), arpabet.strip()))
    return out


def apply(text: str) -> str:
    """The text as the voice should read it. A rule's value is CMU Arpabet for a
    phoneme tag, or, written "=Acab", plain spelling for a voice whose language
    Arpabet doesn't cover (Spanish); either way only what is sent to the voice
    changes, never the script."""
    for rx, value in rules():
        text = rx.sub(lambda m: value[1:] if value.startswith("=") else TAG.format(value), text)
    return text


def respell_rv1909(word: str) -> str:
    """The RV1909 marks a Hebrew name's "ch" as a k sound with a circumflex on the
    next vowel (Achâb, Rachêl, Ezechîas: today's Acab, Raquel, Ezequías). Spelled
    for a Spanish voice: "ch" as "qu" before e and i, "c" before a, o and u. The
    circumflex also falls on the stressed vowel (Ezechîas, Ezequías), so where the
    word has no acute accent of its own it becomes one; where it has (Ochôzías,
    Ocozías) it is dropped."""
    import unicodedata
    acute = not re.search(r"[áéíóúÁÉÍÓÚ]", word)
    plain = ({"â": "á", "ê": "é", "î": "í", "ô": "ó", "û": "ú", "Â": "Á", "Ê": "É", "Î": "Í", "Ô": "Ó", "Û": "Ú"} if acute else
             {"â": "a", "ê": "e", "î": "i", "ô": "o", "û": "u", "Â": "A", "Ê": "E", "Î": "I", "Ô": "O", "Û": "U"})

    def k(m):
        ch, vowel = m.group(1), m.group(2)
        front = unicodedata.normalize("NFD", vowel)[0].lower() in "ei"
        return ("Qu" if ch[0] == "C" else "qu") + vowel if front else ("C" if ch[0] == "C" else "c") + vowel
    out = re.sub(r"([Cc]h)([aeiouáéíóúâêîôû])", k, word)
    return "".join(plain.get(c, c) for c in out)


def write_rv1909(verses: dict) -> int:
    """lexicon/rv1909.tsv: every RV1909 word with a circumflex, respelled by rule."""
    words = sorted({w for vs in verses.values() for t in vs.values() for w in re.findall(r"\w*[âêîôûÂÊÎÔÛ]\w*", t)})
    rows = ["# The RV1909's names spelled for a Spanish voice (generated by `python -m abible lexicon rv1909`;",
            "# see respell_rv1909). Pattern, then =spelling sent to the voice, then the source.",
            "# Checked by ear on the name reel; corrections go below the generated rows."]
    for w in words:
        rows.append(f"{re.escape(w)}\t={respell_rv1909(w)}\tRV1909 circumflex convention (ch as k)")
    FILE.parent.mkdir(parents=True, exist_ok=True)
    FILE.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return len(words)
